# Generated by Django 4.2.3 on 2023-09-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationtype')),
            ],
            options={
                'verbose_name': 'Cause Category',
                'verbose_name_plural': 'Cause Categories',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationtype')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
            },
        ),
        migrations.CreateModel(
            name='HowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.causecategory')),
            ],
            options={
                'verbose_name': 'How Category',
                'verbose_name_plural': 'How Categories',
            },
        ),
        migrations.CreateModel(
            name='HowQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254)),
                ('question_type', models.CharField(max_length=254)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('has_checkbox', models.BooleanField(default=False)),
                ('has_selection', models.BooleanField(default=False)),
                ('has_text', models.BooleanField(default=False)),
                ('has_date', models.BooleanField(default=False)),
                ('has_file', models.BooleanField(default=False)),
                ('has_other_field', models.BooleanField(default=False)),
                ('has_location', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'How Question',
                'verbose_name_plural': 'How Questions',
            },
        ),
        migrations.CreateModel(
            name='WhatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.causecategory')),
            ],
            options={
                'verbose_name': 'What Category',
                'verbose_name_plural': 'What Categories',
            },
        ),
        migrations.CreateModel(
            name='WhatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254)),
                ('question_type', models.CharField(max_length=254)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('has_checkbox', models.BooleanField(default=False)),
                ('has_selection', models.BooleanField(default=False)),
                ('has_text', models.BooleanField(default=False)),
                ('has_date', models.BooleanField(default=False)),
                ('has_file', models.BooleanField(default=False)),
                ('has_other_field', models.BooleanField(default=False)),
                ('has_location', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'What Question',
                'verbose_name_plural': 'What Questions',
            },
        ),
        migrations.CreateModel(
            name='WhatQuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.whatcategory')),
            ],
            options={
                'verbose_name': 'What Title',
                'verbose_name_plural': 'What Titles',
            },
        ),
        migrations.CreateModel(
            name='WhatQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.whatquestion')),
            ],
            options={
                'verbose_name': 'What Question Option',
                'verbose_name_plural': 'What Question Options',
            },
        ),
        migrations.CreateModel(
            name='WhatQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claim')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.whatquestion')),
            ],
            options={
                'verbose_name': 'What Answer',
                'verbose_name_plural': 'What Answers',
            },
        ),
        migrations.AddField(
            model_name='whatquestion',
            name='what_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.whatquestiontitle'),
        ),
        migrations.CreateModel(
            name='HowQuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('how', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.howcategory')),
            ],
            options={
                'verbose_name': 'How Title',
                'verbose_name_plural': 'How Titles',
            },
        ),
        migrations.CreateModel(
            name='HowQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.howquestion')),
            ],
            options={
                'verbose_name': 'How Question Option',
                'verbose_name_plural': 'How Question Options',
            },
        ),
        migrations.CreateModel(
            name='HowQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claim')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.howquestion')),
            ],
            options={
                'verbose_name': 'How Answer',
                'verbose_name_plural': 'How Answers',
            },
        ),
        migrations.AddField(
            model_name='howquestion',
            name='how_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.howquestiontitle'),
        ),
        migrations.CreateModel(
            name='AssessmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=254)),
                ('file', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.assessment')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claim')),
            ],
            options={
                'verbose_name': 'Assessment Note',
                'verbose_name_plural': 'Assessment Notes',
            },
        ),
        migrations.CreateModel(
            name='ApplicationWhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claim')),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.whatcategory')),
            ],
            options={
                'verbose_name': 'Application What',
                'verbose_name_plural': 'Application Whats',
            },
        ),
        migrations.CreateModel(
            name='ApplicationHow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claim')),
                ('how', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.howcategory')),
            ],
            options={
                'verbose_name': 'Application How',
                'verbose_name_plural': 'Application Hows',
            },
        ),
        migrations.CreateModel(
            name='ApplicationCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.causecategory')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claim')),
            ],
            options={
                'verbose_name': 'Application Cause',
                'verbose_name_plural': 'Application Causes',
            },
        ),
    ]
