# Generated by Django 4.2.3 on 2023-09-20 09:39

from django.db import migrations, models
import django.db.models.deletion


def add_status_and_type(apps, schema_editor):
    """Add application status and category info"""
    ApplicationStatus = apps.get_model('application', 'ApplicationStatus')
    ApplicationType = apps.get_model('application', 'ApplicationType')

    ApplicationStatus.objects.create(name='Pending')
    ApplicationStatus.objects.create(name='Completed')
    ApplicationStatus.objects.create(name='Scheduled')

    ApplicationType.objects.create(name='Business')
    ApplicationType.objects.create(name='Personal')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_assigned', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Application Status',
                'verbose_name_plural': 'Application Statuses',
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Application Type',
                'verbose_name_plural': 'Application Types',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('id_number', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('policy_no', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=250)),
                ('contact_no', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
            },
        ),
        migrations.CreateModel(
            name='ClientIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_incident', models.DateTimeField()),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('claim_date_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
            ],
            options={
                'verbose_name': 'Client Incident',
                'verbose_name_plural': 'Client Incidents',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.insuranceprovider'),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=25)),
                ('business_email', models.CharField(max_length=250)),
                ('reg_number', models.CharField(max_length=250)),
                ('vat_number', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=250)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=254)),
                ('scheduled_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('event_id', models.CharField(max_length=254)),
                ('summary', models.CharField(max_length=254)),
                ('link', models.CharField(max_length=254)),
                ('video_link', models.CharField(max_length=254)),
                ('client_location', models.CharField(max_length=254)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='application.application')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('log', models.CharField(max_length=250)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'verbose_name': 'Application Log',
                'verbose_name_plural': 'Application Logs',
            },
        ),
        migrations.RunPython(add_status_and_type)
    ]
