# Generated by Django 4.2.3 on 2023-10-18 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=250)),
                ('room_sid', models.CharField(max_length=250)),
                ('room_status', models.CharField(max_length=250)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.assessment')),
            ],
            options={
                'verbose_name': 'Twilio Room',
                'verbose_name_plural': 'Twilio Rooms',
            },
        ),
        migrations.CreateModel(
            name='TwilioParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_sid', models.CharField(max_length=250)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('twilio_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.twilioroom')),
            ],
            options={
                'verbose_name': 'Twilio Participant',
                'verbose_name_plural': 'Twilio Participants',
            },
        ),
    ]
