# Generated by Django 4.2.3 on 2023-10-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_twilioroom_twilioparticipant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwilioParticipant',
        ),
    ]
