# Generated by Django 4.2.3 on 2023-10-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_delete_twilioparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_sid', models.CharField(max_length=250)),
                ('recording_url', models.CharField(max_length=250)),
                ('twilio_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.twilioroom')),
            ],
            options={
                'verbose_name': 'Twilio Recording',
                'verbose_name_plural': 'Twilio Recordings',
            },
        ),
    ]
