# Generated by Django 4.2.3 on 2023-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_twiliorecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliorecording',
            name='recording_url',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
