# Generated by Django 4.2.3 on 2023-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_twiliorecording_recording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliorecording',
            name='recording_url',
            field=models.CharField(max_length=250),
        ),
    ]
