# Generated by Django 4.2.3 on 2023-10-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_twiliorecording_recording_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='link',
        ),
        migrations.AlterField(
            model_name='client',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.insuranceprovider'),
        ),
    ]
