# Generated by Django 4.2.3 on 2023-09-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationtype')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
        migrations.CreateModel(
            name='SurveyApplicationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Survey Application Title',
                'verbose_name_plural': 'Survey Application Titles',
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_type', to='application.applicationtype')),
            ],
            options={
                'verbose_name': 'Survey Category',
                'verbose_name_plural': 'Survey Categories',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254)),
                ('number', models.IntegerField(default=0)),
                ('question_type', models.CharField(max_length=254)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('has_checkbox', models.BooleanField(default=False)),
                ('has_selection', models.BooleanField(default=False)),
                ('has_text', models.BooleanField(default=False)),
                ('has_date', models.BooleanField(default=False)),
                ('has_file', models.BooleanField(default=False)),
                ('has_other_field', models.BooleanField(default=False)),
                ('has_location', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_application_title', to='surveys.surveyapplicationtitle')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_question', to='surveys.surveyquestion')),
            ],
            options={
                'verbose_name': 'Survey Question Option',
                'verbose_name_plural': 'Survey Question Options',
            },
        ),
        migrations.CreateModel(
            name='SurveyCategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_category', to='surveys.surveycategory')),
            ],
            options={
                'verbose_name': 'Survey Category Type',
                'verbose_name_plural': 'Survey Category Types',
            },
        ),
        migrations.AddField(
            model_name='surveyapplicationtitle',
            name='subcategory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_subcategory_type', to='surveys.surveycategorytype'),
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_application_title', to='surveys.surveyapplicationtitle')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_category', to='surveys.surveycategory')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='surveys.surveyquestion')),
                ('subcategory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_subcategory_type', to='surveys.surveycategorytype')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_application', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Survey Answer',
                'verbose_name_plural': 'Survey Answers',
            },
        ),
    ]
